[package]
name = "cooklatex"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = ["derive"] }
cooklang = { git = "https://github.com/cooklang/cooklang-rs.git"}
toml = "0.9"
